version: '3'

services:
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: ${MARIADB_IMAGE}:${MARIADB_TAG}
    stop_grace_period: 3m
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      ROOT_PASS: ${ROOT_PASS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

  nextcloud:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${NEXTCLOUD_IMAGE}:${NEXTCLOUD_TAG}
    hostname: ${DOMAIN}
    restart: always
    links:
      - mariadb
    depends_on:
      - mariadb
    volumes:
      - data:/data/userdata
      - config:/www/nextcloud/config
      - apps:/data/apps
      - themes:/www/nextcloud/themes
      - logs:/www/logs
      - templates:/data/templates
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_NETWORK: ${NETWORK}
      LETSENCRYPT_HOST: ${DOMAIN}
      TRUSTED_DOMAINS: ${DOMAIN}
      CRON_PERIOD: 5
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      DB_TYPE: mysql
      DB_HOST: ${COMPOSE_PROJECT_NAME}-mariadb
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    cap_add:
      - NET_ADMIN

volumes:
  db:
  data:
  config:
  apps:
  themes:
  logs:
  templates:

networks:
  default:
    name: ${NETWORK}
    external: true