version: '3'

services:
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    image: ${REDIS_IMAGE}:${REDIS_TAG}
    restart: always
    volumes:
      - data:/data/db
      - logs:/data/logs
    environment:
      - CONTAINER_NAME=${COMPOSE_PROJECT_NAME}-server
      - TIMEZONE=${TIMEZONE}
      - ENABLE_LOGS=${ENABLE_LOGS}
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_PASS=${REDIS_PASS}
    labels:
      # Habilita Traefik para TCP (no HTTP)
      - "traefik.enable=true"
      # Regla de enrutamiento TCP (HostSNI para distinguir instancias)
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-redis.rule=HostSNI(`redis.${DOMAIN}`) || HostSNI(`www.redis.${DOMAIN}`)"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-redis.entrypoints=redis"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-redis.tls=true"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-redis.tls.certresolver=letsencrypt"
      # Backend (puerto de Redis)
      - "traefik.tcp.services.${COMPOSE_PROJECT_NAME}-pg.loadbalancer.server.port=6379"

  insight:
    container_name: ${COMPOSE_PROJECT_NAME}-insight
    image: ${INSIGHT_IMAGE}:${INSIGHT_TAG}
    restart: always
    depends_on:
      - redis
    environment:
      RI_APP_HOST: 0.0.0.0
      RI_APP_PORT: ${INSIGHT_PORT}
      RI_LOG_LEVEL: ${RI_LOG_LEVEL}
      RI_FILES_LOGGER: ${RI_FILES_LOGGER}
      RI_STDOUT_LOGGER: ${RI_STDOUT_LOGGER}
    volumes:
      - insight:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-insight.rule=Host(`pg.${DOMAIN}`) || Host(`www.pg.${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-insight.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-insight.middlewares=insight-https-redirect"
      - "traefik.http.middlewares.insight-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.insight.rule=Host(`redis.${DOMAIN}`) || Host(`www.redis.${DOMAIN}`)"
      - "traefik.http.routers.insight.entrypoints=websecure"
      - "traefik.http.routers.insight.tls=true"
      - "traefik.http.routers.insight.tls.certresolver=letsencrypt"
      - "traefik.http.services.insight.loadbalancer.server.port=5540"
      
volumes:
  data:
  logs:
  insight:

networks:
  default:
    name: ${NETWORK}
    external: true
