version: '3'

services:
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}-mongo
    image: mongo:${MONGO_TAG}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - mongo-logs:/var/log/mongodb
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  elasticsearch:
    container_name: ${COMPOSE_PROJECT_NAME}-elasticsearch
    image: elasticsearch:${ELASTICSEARCH_TAG}
    restart: always
    environment:
      - cluster.name=elasticsearch
      - discovery.type=${DISCOVERY_TYPE}
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
    mem_limit: ${MEMORY_LIMIT}
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -fsSL http://localhost:9200/_cat/health?h=status | grep -q -E 'green|yellow'"
      ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1m

  gateway:
    container_name: ${COMPOSE_PROJECT_NAME}-gateway
    image: graviteeio/apim-gateway:${VERSION_TAG}
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      # - mongodb
      # - elasticsearch
      - mongodb:
          condition: service_healthy
      - elasticsearch:
          condition: service_healthy
    volumes:
      - gateway-logs:/opt/graviteeio-gateway/logs
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_ratelimit_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_reporters_elasticsearch_endpoints_0=http://elasticsearch:9200
      #- gravitee_management_type=mongodb
      #- gravitee_http_secured=true
      #- gravitee_http_ssl_clientAuth=request
      #- gravitee_http_ssl_keystore_type=pkcs12
      #- gravitee_http_ssl_keystore_path=/opt/graviteeio-gateway/certificates/server.p12
      #- gravitee_http_ssl_keystore_password=server-secret
      #- gravitee_http_ssl_truststore_type=pkcs12
      #- gravitee_http_ssl_truststore_path=/opt/graviteeio-gateway/certificates/ca.p12
      #- gravitee_http_ssl_truststore_password=ca-secret
      - VIRTUAL_PORT: 8082
      - VIRTUAL_HOST: ${GATEWAY_URL}
      - LETSENCRYPT_HOST: ${GATEWAY_URL}

volumes:
  mongo-data:
  mongo-logs:
  elasticsearch-data:
  gateway-logs:

networks:
  default:
    name: ${NETWORK}
    external: true
