services:
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: ${MARIADB_IMAGE}:${MARIADB_TAG}
    hostname: ${COMPOSE_PROJECT_NAME}-mariadb
    stop_grace_period: 3m
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
      - mariadb-logs:/logs
    environment:
      CONTAINER_NAME: ${COMPOSE_PROJECT_NAME}-mariadb
      TIMEZONE: ${TIMEZONE}
      ROOT_PASS: ${ROOT_PASS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    labels:
      # Habilita Traefik para TCP (no HTTP)
      - "traefik.enable=true"
      # Regla de enrutamiento TCP (HostSNI para distinguir instancias)
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mariadb.rule=HostSNI(`${URL}`) || HostSNI(`www.${URL}`)"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mariadb.entrypoints=mariadb"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mariadb.tls=true"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mariadb.tls.certresolver=letsencrypt"
      # Backend (puerto de MariaDB)
      - "traefik.tcp.services.${COMPOSE_PROJECT_NAME}-mariadb.loadbalancer.server.port=3306"

volumes:
  mariadb-data:
  mariadb-logs:

networks:
  default:
    name: ${NETWORK}
    external: true
