version: '3'

services:
  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    hostname: ${COMPOSE_PROJECT_NAME}-postgres
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    restart: always
    environment:
      TIMEZONE: ${TIMEZONE}
      INITDB_LOCALE: ${INITDB_LOCALE}
      INITDB_ENCODING: ${INITDB_ENCODING}
      INITDB_LC_COLLATE: ${INITDB_LC_COLLATE}
      INITDB_LC_CTYPE: ${INITDB_LC_CTYPE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SUPERUSER_USER: ${SUPERUSER_USER}
      SUPERUSER_PASS: ${SUPERUSER_PASS}
      DB_EXTENSION: ${DB_EXTENSION}
      LISTEN_IP: ${LISTEN_IP}
      LISTEN_PORT: ${LISTEN_PORT}
      ENABLE_REPLICATION: ${ENABLE_REPLICATION}
      REPLICATION_MODE: ${REPLICATION_MODE}
      REPLICATION_HOST: ${REPLICATION_HOST}
      REPLICATION_PORT: ${REPLICATION_PORT}
      REPLICATION_USER: ${REPLICATION_USER}
      REPLICATION_PASS: ${REPLICATION_PASS}
      CONTAINER_ENABLE_MONITORING: ${CONTAINER_ENABLE_MONITORING}
      MONITOR_USER: ${MONITOR_USER}
      MONITOR_PASS: ${MONITOR_PASS}
    volumes:
      - postgres-logs:/logs
      - postgres-data:/var/lib/postgresql/data
    labels:
      # Habilita Traefik para TCP (no HTTP)
      - "traefik.enable=true"
      # Regla de enrutamiento TCP (HostSNI para distinguir instancias)
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-postgres.rule=HostSNI(`postgres.${URL}`) || HostSNI(`www.postgres.${URL}`)"  # Ej: pg-instancia1.tudominio.com
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-postgres.entrypoints=postgres"  # Entrypoint TCP definido en Traefik
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-postgres.tls=true"  # Opcional: TLS para seguridad
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-postgres.tls.certresolver=letsencrypt"
      # Backend (puerto de PostgreSQL)
      - "traefik.tcp.services.${COMPOSE_PROJECT_NAME}-postgres.loadbalancer.server.port=5432"

volumes:
  postgres-data:
  postgres-logs:

networks:
  default:
    name: ${NETWORK}
    external: true
