services:
  pihole:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: ${PIHOLE_IMAGE}:${PIHOLE_TAG}
    restart: unless-stopped
    hostname: ${PIHOLE_HOSTNAME}
    network_mode: host
    volumes:
      - pihole-data:/etc/pihole
      - dnsmasq-data:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TZ}
      DNSMASQ_LISTENING: all
      PIHOLE_DOCKER_TAG: ${PIHOLE_TAG}
      FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      PROXY_LOCATION: ${PIHOLE_HOSTNAME}
      WEBPASSWORD: ${WEBPASSWORD}
      WEB_PORT: 80
      VIRTUAL_PORT: 80
      CORS_HOSTS: ${PIHOLE_URL}
      VIRTUAL_HOST: ${PIHOLE_URL},www.${PIHOLE_URL}
      LETSENCRYPT_HOST: ${PIHOLE_URL},www.${PIHOLE_URL}
    extra_hosts:
      - '${PIHOLE_HOSTNAME} ${PIHOLE_URL}:${FTLCONF_LOCAL_IPV4}'
      # LAN hostnames for other docker containers using nginx-proxy
      - '${PIHOLE_URL}.lan:${FTLCONF_LOCAL_IPV4}'
      
volumes:
  pihole-data:
  dnsmasq-data:
