services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: ${MYSQL_IMAGE}:${MYSQL_TAG}
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    labels:
      # Habilita Traefik para TCP (no HTTP)
      - "traefik.enable=true"
      # Regla de enrutamiento TCP (HostSNI para distinguir instancias)
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mysql.rule=HostSNI(`mysql.${DOMAIN}`) || HostSNI(`www.mysql.${DOMAIN}`)"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mysql.entrypoints=mysql"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mysql.tls=true"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mysql.tls.certresolver=letsencrypt"
      # Backend (puerto de MySQL)
      - "traefik.tcp.services.${COMPOSE_PROJECT_NAME}-mysql.loadbalancer.server.port=3306"

  gitea:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${GITEA_IMAGE}:${GITEA_TAG}
    restart: always
    depends_on:
      - db
    volumes:
      - cache:/tmp/buildx-cache
      - config:/etc/gitea
      - custom:/data/gitea/custom
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      USER: ${USER}
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: ${COMPOSE_PROJECT_NAME}-mysql:3306
      GITEA__database__NAME: ${MYSQL_DATABASE}
      GITEA__database__USER: ${MYSQL_USER}
      GITEA__database__PASSWD: ${MYSQL_PASSWORD}
      GITEA__mailer__ENABLED: ${MAILER_ENABLED}
      GITEA__mailer__FROM: ${GITEA_FROM}
      GITEA__mailer__PROTOCOL: ${GITEA_PROTOCOL}
      GITEA__mailer__SMTP_ADDR: ${GITEA_SMTP_ADDR}
      GITEA__mailer__SMTP_PORT: ${GITEA_SMTP_PORT}
      GITEA__mailer__USER: ${GITEA_USER}
      GITEA__mailer__PASSWD: ${GITEA_PASSWD}
    labels:
      # Habilita Traefik para HTTP (no TCP)
      - "traefik.enable=true"
      # HTTP → HTTPS (middleware definido en https_redirection.yml)
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.middlewares=https_redirection@file"
      # HTTPS (SSL automático)
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
      # Servicio backend (puerto Gitea)
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"

volumes:
  cache:
  config:
  custom:
  data:
  db:

networks:
  default:
    name: ${NETWORK}
    external: true
