version: '3'
services:
  openldap:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${LDAP_IMAGE}:${LDAP_TAG}
    hostname: ${OPENLDAP_HOSTNAME}
    restart: always
    ports:
      - ${LDAP_PORT}:389
      - ${LDAPS_PORT}:636
    environment:
      HOSTNAME: ${OPENLDAP_HOSTNAME}
      ORGANIZATION: ${ORGANIZATION}
      SCHEMA_TYPE: ${SCHEMA_TYPE}
      LOG_LEVEL: 256
      DOMAIN: ${DOMAIN}
      BASE_DN: ${BASE_DN}
      ADMIN_PASS: ${ADMIN_PASS}
      CONFIG_PASS: ${CONFIG_PASS}
      DEBUG_MODE: false
      ENABLE_READONLY_USER: false
      READONLY_USER_USER: ${READONLY_USER_USER}
      READONLY_USER_PASS: ${READONLY_USER_PASS}
      CONTAINER_ENABLE_MONITORING: true
      CONTAINER_NAME: openldap
    volumes:
      - backup:/data/backup
      - data:/var/lib/openldap
      - config:/etc/openldap/slapd.d

  phpldapadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-phpldapadmin
    image: ${PHPLDAPADMIN_IMAGE}:${PHPLDAPADMIN_TAG}
    restart: always
    depends_on:
      - openldap
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${OPENLDAP_HOSTNAME}
      PHPLDAPADMIN_HTTPS: false
      VIRTUAL_HOST: ${PHPLDAPADMIN_HOSTNAME}
      LETSENCRYPT_HOST: ${PHPLDAPADMIN_HOSTNAME}

volumes:
  data:
  backup:
  config:

networks:
  default:
    name: ${NETWORK}
    external: true
