version: '3'

services:
  unbound:
    container_name: ${COMPOSE_PROJECT_NAME}-unbound
    image: mvance/unbound:${UNBOUND_TAG}
    restart: unless-stopped
    hostname: unbound
    volumes:
      - unbound-data:/opt/unbound/etc/unbound/
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: ${UNBOUND_IP}
      default:

  pihole:
    container_name: ${COMPOSE_PROJECT_NAME}-pihole
    image: pihole/pihole:${PIHOLE_TAG}
    restart: unless-stopped
    hostname: pihole
    depends_on:
      - unbound
    dns:
      - 127.0.0.1
      - ${UNBOUND_IP}
    volumes:
      - pihole-data:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${WEBPASSWORD}
      VIRTUAL_HOST: ${PIHOLE_URL}
      LETSENCRYPT_HOST: ${PIHOLE_URL}
    networks:
      private_network:
        ipv4_address: ${PIHOLE_IP}
      default:

  wireguard:
    container_name: ${COMPOSE_PROJECT_NAME}-wireguard
    image: linuxserver/wireguard:${WIREGUARD_TAG}
    restart: unless-stopped
    depends_on:
      - unbound
      - pihole
    ports:
      - 5000:5000
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    environment:
      TZ: ${TIMEZONE}
      PUID: ${PUID}
      PGID: ${PGID}
      SERVERURL: ${WIREGUARD_URL}
      SERVERPORT: 51820
      PEERS: 1
      PEERDNS: ${PIHOLE_IP}
    volumes:
      - wireguard-config:/config

  wireguard-ui:
    container_name: ${COMPOSE_PROJECT_NAME}-wireguard-ui
    image: ngoduykhanh/wireguard-ui:${WIREGUARD_UI_TAG}
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - wireguard-ui-db:/app/db
      - wireguard-ui-config:/config

volumes:
  unbound-data:
  pihole-data:
  dnsmasq:
  wireguard-config:
  wireguard-ui-db:
  wireguard-ui-config:

networks:
  default:
    name: ${NETWORK}
    external: true
  private_network:
    name: ${PRIVATE_NETWORK}
    ipam:
      driver: default
      config:
        - subnet: ${PRIVATE_NETWORK_SUBNET}